version: '2'
services:
  tasks:
    build: "../../tasks"
    environment:
      - TASKSERVICE_SERVICE_PORT=7878
    ports:
      - 3001:7878

  web:
    build: "../../web"
    environment:
      - WEBSERVICE_SERVICE_PORT=3000
    ports:
      - 3000:3000